<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TargetEndpoint name="sync-wrap">
  <PreFlow>
    <Request>
      <Step>
        <Name>OauthV2.VerifyAccessToken</Name>
      </Step>
      <Step>
        <Name>Quota</Name>
      </Step>
      <Step>
        <Name>SpikeArrest</Name>
      </Step>
      <Step>
        <Name>AssignMessage.AddSyncWaitHeader</Name>
        <Condition>(request.header.X-Sync-Wait.1 LesserThan 0.25) OR (request.header.X-Sync-Wait.1 GreaterThan 29) OR (request.header.X-Sync-Wait.1 Is null)</Condition>
      </Step>
    </Request>
  </PreFlow>
  <LocalTargetConnection>
    <APIProxy>sync-wrap-{{ APIGEE_ENVIRONMENT }}</APIProxy>
    <ProxyEndpoint>default</ProxyEndpoint>
    <Path>/sync-wrap/{{ SERVICE_BASE_PATH }}</Path>
  </LocalTargetConnection>
  <FaultRules>
    <FaultRule name="pass_through">
      <Condition>(response.status.code Equals 4*)</Condition>
      <Step>
        <!-- No-op fault rule. Prevent 4xx entering error state. -->
        <Condition>(response.status.code Equals "504")</Condition>
        <Name>Quota</Name>
      </Step>
    </FaultRule>
    <FaultRule name="request_timeout">
      <Condition>(response.status.code Equals "504")</Condition>
      <Step>
        <Name>RaiseFault.RequestTimeout</Name>
      </Step>
    </FaultRule>
    <FaultRule name="access_token_expired">
      <Step>
        <Name>ExtractVariables.OAuthErrorFaultString</Name>
      </Step>
      <Step>
        <Name>AssignMessage.Errors.OAuthPolicyResponse</Name>
      </Step>
      <Condition>oauthV2.OauthV2.VerifyAccessToken.failed</Condition>
    </FaultRule>
  </FaultRules>
  <DefaultFaultRule>
    <Step>
      <Name>AssignMessage.Errors.CatchAllMessage</Name>
    </Step>
  </DefaultFaultRule>
</TargetEndpoint>